// Generated by weglet/ui/generate_contract.py. Do not edit.
// Source: weglet/ui/contract.json

// Weglet's own addresses, in the form the user sees them. The
// browser process maps each to a real chrome://weglet/ page --
// see weglet/browser/weglet_window.cc's ResolveForEngine, which is
// generated from the same source so the two cannot list a
// different set again.
pub const BLANK_TAB: &str = "about:blank";
pub const SETTINGS_ADDRESS: &str = "weglet://settings";
pub const HISTORY_ADDRESS: &str = "weglet://history";
pub const BOOKMARKS_ADDRESS: &str = "weglet://bookmarks";

// A page of ours, in the form the user types it. Deliberately exact
// matches: a prefix test would make "weglet://settings.evil.example"
// one of our pages.
pub fn is_internal_address(url: &str) -> bool {
    matches!(
        url,
        BLANK_TAB | SETTINGS_ADDRESS | HISTORY_ADDRESS | BOOKMARKS_ADDRESS
    )
}
