#!/usr/bin/env python3
# Copyright 2026 Weglet - Licensed under Apache 2.0
#
# weglet/ui/build_ui.py
#
# Builds the interface and embeds it into the binary.
#
# Three steps, in order:
#   1. generate_tokens.py turns tokens.json into CSS, TypeScript and a
#      C++ header. The CSS carries the @font-face rules; the font files
#      themselves are embedded in step 3 alongside the pages.
#   2. Chromium's vendored TypeScript compiles src/*.ts to ES modules.
#      Vendored, so there is no npm install and no node_modules here.
#   3. The pages, styles and compiled scripts are written into a generated
#      C++ file as byte arrays.
#
# Step 3 rather than grit because the set of files is small and entirely
# ours: a generated array is one script we control, where grit would be a
# .grd file, a resource-id header and a second packing step to keep in
# step with it.

import argparse
import json
import os
import subprocess
import sys

# weglet/build_support.py -- find_node_toolchain and write_depfile, which
# every build script here needs and which used to exist twice.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import build_support  # noqa: E402

# Extension -> what the protocol handler should answer with. A file whose
# type is not here is a mistake rather than something to serve as bytes:
# guessing a MIME type is how a page ends up rendered as plain text.
MIME_TYPES = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "text/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    # Only what the pages actually serve. .ttf is deliberately absent:
    # content's own WebUIDataSourceImpl::GetMimeType has no entry for it
    # and falls through to text/html, so a .ttf here would be embedded
    # successfully and served as the wrong type. woff2 is in its table.
    ".woff2": "font/woff2",
}


def run(command: list[str], cwd: str | None = None) -> None:
    result = subprocess.run(command, cwd=cwd)
    if result.returncode != 0:
        raise SystemExit(result.returncode)



def compile_typescript(ui_dir: str, out_dir: str, chromium_root: str) -> None:
    node, tsc = build_support.find_node_toolchain(chromium_root)
    run(
        [
            node,
            tsc,
            "--project",
            os.path.join(ui_dir, "tsconfig.json"),
            "--outDir",
            out_dir,
            # Not from tsconfig.json: the output directory is the build
            # directory, which tsconfig has no business knowing about.
            "--rootDir",
            os.path.join(ui_dir, "src"),
        ]
    )


def c_identifier(name: str) -> str:
    return "".join(char if char.isalnum() else "_" for char in name)


def embed(files: dict[str, bytes], header_out: str, source_out: str) -> None:
    """Writes the file set as a lookup table in generated C++."""
    header = [
        "// Generated by weglet/ui/build_ui.py. Do not edit.",
        "",
        "#ifndef WEGLET_UI_GENERATED_RESOURCES_H_",
        "#define WEGLET_UI_GENERATED_RESOURCES_H_",
        "",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace weglet::ui {",
        "",
        "struct Resource {",
        "  std::string_view path;",
        "  std::string_view mime_type;",
        "  std::string_view contents;",
        "};",
        "",
        "// Nullptr-terminated is avoided on purpose: the count is exact, so",
        "// a lookup cannot run past the end.",
        "extern const Resource kResources[];",
        "extern const size_t kResourceCount;",
        "",
        "// The resource at `path`, or nullptr. `path` has no leading slash.",
        "const Resource* Find(std::string_view path);",
        "",
        "}  // namespace weglet::ui",
        "",
        "#endif  // WEGLET_UI_GENERATED_RESOURCES_H_",
    ]

    source = [
        "// Generated by weglet/ui/build_ui.py. Do not edit.",
        "",
        '#include "weglet/ui/generated_resources.h"',
        "",
        "#include <algorithm>",
        "#include <cstdint>",
        "",
        "namespace weglet::ui {",
        "namespace {",
        "",
    ]

    # Each file as its own array, so the compiler is not asked to parse one
    # enormous initialiser.
    for path in sorted(files):
        data = files[path]
        symbol = f"k{c_identifier(path)}"
        octets = ", ".join(f"0x{byte:02x}" for byte in data)
        # uint8_t, not char: char is signed here, and a font file has bytes
        # above 127 that do not fit in it -- which is a narrowing error, not
        # a warning. Reinterpreted back to char at the string_view below,
        # where the width is what matters and the sign is not.
        source += [
            f"// {path} ({len(data)} bytes)",
            f"constexpr uint8_t {symbol}[] = {{{octets}}};",
            "",
        ]

    source += ["}  // namespace", "", "const Resource kResources[] = {"]
    for path in sorted(files):
        extension = os.path.splitext(path)[1]
        mime = MIME_TYPES.get(extension)
        if mime is None:
            raise SystemExit(
                f"no MIME type registered for {extension!r} ({path}).\n"
                "Add it to MIME_TYPES in build_ui.py -- serving a file with a\n"
                "guessed type is how a page renders as plain text.\n"
            )
        symbol = f"k{c_identifier(path)}"
        source.append(
            f'    {{"{path}", "{mime}", '
            f"std::string_view(reinterpret_cast<const char*>({symbol}), "
            f"sizeof({symbol}))}},"
        )
    source += [
        "};",
        "",
        f"const size_t kResourceCount = {len(files)};",
        "",
        "const Resource* Find(std::string_view path) {",
        "  const auto* end = kResources + kResourceCount;",
        "  const auto* found = std::find_if(",
        "      kResources, end,",
        "      [path](const Resource& resource) { return resource.path == path; });",
        "  return found == end ? nullptr : found;",
        "}",
        "",
        "}  // namespace weglet::ui",
    ]

    write_text(header_out, "\n".join(header) + "\n")
    write_text(source_out, "\n".join(source) + "\n")


def write_text(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # Unchanged output keeps its timestamp, or ninja rebuilds everything
    # downstream on every run.
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            if handle.read() == contents:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def collect(directories: list[str]) -> dict[str, bytes]:
    """Every servable file, keyed by the path a page requests it under."""
    files: dict[str, bytes] = {}
    for directory in directories:
        if not os.path.isdir(directory):
            continue
        for name in sorted(os.listdir(directory)):
            full = os.path.join(directory, name)
            if not os.path.isfile(full):
                continue
            if os.path.splitext(name)[1] not in MIME_TYPES:
                continue
            if name in files:
                raise SystemExit(
                    f"two files want to be served as {name!r}. Page paths are"
                    " flat, so the names have to be unique.\n"
                )
            with open(full, "rb") as handle:
                files[name] = handle.read()
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ui-dir", required=True, help="weglet/ui")
    parser.add_argument("--chromium-root", required=True)
    parser.add_argument("--gen-dir", required=True, help="where to generate")
    parser.add_argument("--header", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--depfile")
    args = parser.parse_args()

    ui_dir = os.path.abspath(args.ui_dir)
    gen_dir = os.path.abspath(args.gen_dir)
    scripts_dir = os.path.join(gen_dir, "scripts")

    # 1. Tokens. The CSS lands next to the pages so a page can link it; the
    #    TypeScript lands with the sources so an import resolves.
    run(
        [
            sys.executable,
            os.path.join(ui_dir, "generate_tokens.py"),
            "--tokens",
            os.path.join(ui_dir, "tokens.json"),
            "--css",
            os.path.join(gen_dir, "pages", "tokens.css"),
            "--ts",
            os.path.join(ui_dir, "src", "tokens.ts"),
            "--header",
            os.path.join(gen_dir, "weglet_tokens.h"),
        ]
    )

    # 1b. Contract: message names, page paths and internal addresses. The
    #     TypeScript side (contract.ts) lands with the sources so
    #     protocol.ts's import resolves, same as tokens.ts above. The C++
    #     header lands in gen/ for the browser process; the Rust output is
    #     not requested here at all -- weglet-core gets its own copy
    #     through rust/build_rust.py, which runs independently of this
    #     script and has to work under a plain `cargo build` with no GN
    #     action having run first.
    run(
        [
            sys.executable,
            os.path.join(ui_dir, "generate_contract.py"),
            "--contract",
            os.path.join(ui_dir, "contract.json"),
            "--ts",
            os.path.join(ui_dir, "src", "contract.ts"),
            "--header",
            os.path.join(gen_dir, "generated_contract.h"),
        ]
    )

    # 2. TypeScript.
    compile_typescript(ui_dir, scripts_dir, os.path.abspath(args.chromium_root))

    # 3. Embed. Static pages first so a generated file with the same name
    #    would be caught as a duplicate rather than silently winning.
    files = collect(
        [
            os.path.join(ui_dir, "pages"),
            os.path.join(ui_dir, "fonts"),
            os.path.join(gen_dir, "pages"),
            scripts_dir,
        ]
    )
    if not files:
        raise SystemExit("no UI files to embed -- something built nothing.\n")
    embed(files, args.header, args.source)

    if args.depfile:
        # Every page, script, font and generator input: a change to any of
        # them has to rebuild the embedded resource set.
        build_support.write_depfile(
            args.depfile,
            args.source,
            ui_dir,
            lambda name: os.path.splitext(name)[1] in (*MIME_TYPES, ".ts", ".py")
            or name in ("tokens.json", "tsconfig.json", "contract.json"),
        )
    return 0



if __name__ == "__main__":
    sys.exit(main())
