#!/usr/bin/env python3
# Copyright 2026 Weglet - Licensed under Apache 2.0
#
# weglet/ui/generate_tokens.py
#
# Turns tokens.json into the three forms the codebase needs. Run by the
# build, never by hand -- the generated files are build output and are not
# checked in, so there is no way for them to drift from the source.

import argparse
import json
import os
import sys

# Groups whose values are pixel counts. CSS wants "8px", TypeScript and
# C++ want 8.
_PIXEL_GROUPS = {"space", "radius", "layout"}
_MS_GROUPS = {"motion"}


def load(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def entries(tokens: dict):
    """Yields (group, name, value), skipping the $comment documentation."""
    for group, values in tokens.items():
        if group.startswith("$"):
            continue
        for name, value in values.items():
            if name.startswith("$"):
                continue
            yield group, name, value


def css_value(group: str, name: str, value) -> str:
    if group == "radius" and name == "pill":
        # A pill is "as round as it gets", not 999 pixels of anything.
        return "9999px"
    if group in _PIXEL_GROUPS:
        return f"{value}px"
    if group in _MS_GROUPS:
        return f"{value}ms"
    if group == "font" and name.startswith("size-"):
        return f"{value}px"
    return str(value)


def write_css(tokens: dict, out: str) -> None:
    lines = [
        "/* Generated by weglet/ui/generate_tokens.py. Do not edit.",
        " * Source: weglet/ui/tokens.json",
        " */",
        ":root {",
    ]
    for group, name, value in entries(tokens):
        lines.append(f"  --{group}-{name}: {css_value(group, name, value)};")
    lines.append("}")
    write(out, "\n".join(lines) + "\n")


def ts_name(group: str, name: str) -> str:
    """group-name -> groupName, with digits kept where they are."""
    parts = f"{group}-{name}".split("-")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def write_ts(tokens: dict, out: str) -> None:
    lines = [
        "// Generated by weglet/ui/generate_tokens.py. Do not edit.",
        "// Source: weglet/ui/tokens.json",
        "",
        "// Only for values code has to compute with. Anything that is just",
        "// applied to an element belongs in CSS, through the custom",
        "// properties in tokens.css.",
        "export const tokens = {",
    ]
    for group, name, value in entries(tokens):
        rendered = f'"{value}"' if isinstance(value, str) else str(value)
        lines.append(f"  {ts_name(group, name)}: {rendered},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type TokenName = keyof typeof tokens;")
    write(out, "\n".join(lines) + "\n")


def cpp_name(group: str, name: str) -> str:
    """layout-toolbar-height -> kLayoutToolbarHeight."""
    parts = f"{group}-{name}".split("-")
    return "k" + "".join(part.capitalize() for part in parts)


def write_header(tokens: dict, out: str) -> None:
    lines = [
        "// Generated by weglet/ui/generate_tokens.py. Do not edit.",
        "// Source: weglet/ui/tokens.json",
        "",
        "#ifndef WEGLET_UI_TOKENS_H_",
        "#define WEGLET_UI_TOKENS_H_",
        "",
        "namespace weglet::tokens {",
        "",
        "// Logical pixels, the same unit the CSS in the pages uses. The",
        "// window layer converts to device pixels once, at the boundary.",
    ]
    # Only the numeric groups. A C++ constant for a hex colour string would
    # be a colour the C++ side is not the one drawing.
    for group, name, value in entries(tokens):
        if group not in _PIXEL_GROUPS and group not in _MS_GROUPS:
            continue
        lines.append(f"inline constexpr int {cpp_name(group, name)} = {value};")
    lines += [
        "",
        "}  // namespace weglet::tokens",
        "",
        "#endif  // WEGLET_UI_TOKENS_H_",
    ]
    write(out, "\n".join(lines) + "\n")


def write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # Only touch the file when it actually changes: a rewritten timestamp
    # makes ninja rebuild everything downstream for nothing.
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            if handle.read() == contents:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tokens", required=True)
    parser.add_argument("--css", required=True)
    parser.add_argument("--ts", required=True)
    parser.add_argument("--header", required=True)
    args = parser.parse_args()

    tokens = load(args.tokens)
    write_css(tokens, args.css)
    write_ts(tokens, args.ts)
    write_header(tokens, args.header)
    return 0


if __name__ == "__main__":
    sys.exit(main())
