#!/usr/bin/env python3
# Copyright 2026 Weglet - Licensed under Apache 2.0
#
# ui/i18n/*.txt -> a TypeScript module of translation tables.
#
# One file per language, one "key=value" per line. en.txt is the
# template every other file is checked against. A key missing from a
# translation falls back to en.txt's value (never blank, never the raw
# key) with a stderr warning -- shipping a partial translation isn't an
# error. A key a translation has that en.txt doesn't is a build failure
# (a typo or stale key).

import argparse
import glob
import os
import sys

TEMPLATE_LANGUAGE = "en"


def parse_language_file(path: str) -> dict[str, str]:
    entries: dict[str, str] = {}
    with open(path, encoding="utf-8") as handle:
        for lineno, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                raise SystemExit(f"{path}:{lineno}: not a 'key=value' line: {raw_line!r}\n")
            key, value = line.split("=", 1)
            key = key.strip()
            if not key:
                raise SystemExit(f"{path}:{lineno}: empty key\n")
            if key in entries:
                raise SystemExit(f"{path}:{lineno}: duplicate key {key!r}\n")
            entries[key] = value.strip()
    return entries


def language_of(path: str) -> str:
    return os.path.splitext(os.path.basename(path))[0]


def load_languages(i18n_dir: str) -> dict[str, dict[str, str]]:
    paths = sorted(glob.glob(os.path.join(i18n_dir, "*.txt")))
    if not paths:
        raise SystemExit(f"no language files found under {i18n_dir}\n")

    languages = {language_of(path): parse_language_file(path) for path in paths}
    if TEMPLATE_LANGUAGE not in languages:
        raise SystemExit(
            f"{i18n_dir} has no {TEMPLATE_LANGUAGE}.txt -- it is the template "
            "every other language is checked against, and has to exist\n"
        )
    return languages


def resolve(languages: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    """Every language, filled out to the template's full key set. See the
    module docstring for what's an error and what's a warning."""
    template = languages[TEMPLATE_LANGUAGE]
    resolved: dict[str, dict[str, str]] = {TEMPLATE_LANGUAGE: dict(template)}

    for lang, entries in languages.items():
        if lang == TEMPLATE_LANGUAGE:
            continue
        unknown = sorted(set(entries) - set(template))
        if unknown:
            raise SystemExit(
                f"{lang}.txt has {len(unknown)} key(s) not in {TEMPLATE_LANGUAGE}.txt "
                f"(typo, or a key removed from the template without updating "
                f"this file?): {', '.join(unknown)}\n"
            )
        missing = sorted(set(template) - set(entries))
        if missing:
            print(
                f"generate_i18n.py: {lang}.txt is missing {len(missing)} of "
                f"{len(template)} keys, falling back to {TEMPLATE_LANGUAGE}.txt "
                f"for: {', '.join(missing)}",
                file=sys.stderr,
            )
        filled = dict(template)
        filled.update(entries)
        resolved[lang] = filled
    return resolved


def write_ts(languages: dict[str, dict[str, str]], out: str) -> None:
    order = [TEMPLATE_LANGUAGE] + sorted(lang for lang in languages if lang != TEMPLATE_LANGUAGE)
    lines = [
        "// Generated by weglet/ui/generate_i18n.py. Do not edit.",
        "// Source: weglet/ui/i18n/*.txt",
        "",
        "export const LANGUAGES = [",
    ]
    for lang in order:
        lines.append(f'  "{lang}",')
    lines += [
        "] as const;",
        "",
        "export type Language = (typeof LANGUAGES)[number];",
        "",
        "// Every language filled out to the same full set of keys --",
        "// see generate_i18n.py for how a partial translation gets there.",
        "export const TRANSLATIONS: Readonly<Record<Language, Readonly<Record<string, string>>>> = {",
    ]
    for lang in order:
        lines.append(f"  {lang}: {{")
        for key, value in languages[lang].items():
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{key}": "{escaped}",')
        lines.append("  },")
    lines.append("};")
    write(out, "\n".join(lines) + "\n")


def write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # Only touch the file when it changes: a rewritten timestamp makes
    # ninja rebuild everything downstream.
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            if handle.read() == contents:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--i18n-dir", required=True)
    parser.add_argument("--ts", required=True)
    args = parser.parse_args()

    languages = load_languages(args.i18n_dir)
    resolved = resolve(languages)
    write_ts(resolved, args.ts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
