#!/usr/bin/env python3
# Copyright 2026 Weglet - Licensed under Apache 2.0
#
# weglet/ui/generate_tokens.py
#
# Turns tokens.json into the three forms the codebase needs. Run by the
# build, never by hand -- the generated files are build output and are not
# checked in, so there is no way for them to drift from the source.

import argparse
import json
import os
import sys

# Groups whose values are pixel counts. CSS wants "8px", TypeScript and
# C++ want 8.
_PIXEL_GROUPS = {"space", "radius", "layout"}
_MS_GROUPS = {"motion"}


def load(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def entries(tokens: dict):
    """Yields (group, name, value), skipping the $comment documentation."""
    for group, values in tokens.items():
        if group.startswith("$") or not isinstance(values, dict):
            continue
        for name, value in values.items():
            if name.startswith("$"):
                continue
            yield group, name, value


def css_value(group: str, name: str, value) -> str:
    if group == "radius" and name == "pill":
        # A pill is "as round as it gets", not 999 pixels of anything.
        return "9999px"
    if group in _PIXEL_GROUPS:
        return f"{value}px"
    if group in _MS_GROUPS:
        return f"{value}ms"
    if group == "font" and name.startswith("size-"):
        return f"{value}px"
    return str(value)


# Colours that exist only as a mix of two others. Kept out of tokens.json
# because they are not values anybody chooses -- they are derived, and
# writing them out by hand means two numbers to keep in step.
_DERIVED_CSS = [
    "  /* The hover and pressed tints: the ring colour bled into the field,",
    "     so a hovered control looks lit from within rather than repainted. */",
    "  --color-surface-hover: color-mix(in srgb, var(--color-ring) 25%, var(--color-field));",
    "  --color-surface-pressed: color-mix(in srgb, var(--color-ring) 40%, var(--color-field));",
]


def write_css(tokens: dict, out: str) -> None:
    lines = [
        "/* Generated by weglet/ui/generate_tokens.py. Do not edit.",
        " * Source: weglet/ui/tokens.json",
        " */",
        ":root {",
    ]
    for group, name, value in entries(tokens):
        lines.append(f"  --{group}-{name}: {css_value(group, name, value)};")
    lines += _DERIVED_CSS
    lines.append("}")
    lines += _FONT_FACES
    write(out, "\n".join(lines) + "\n")


def ts_name(group: str, name: str) -> str:
    """group-name -> groupName, with digits kept where they are."""
    parts = [p for p in f"{group}-{name}".split("-") if p]
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


# Shipped with the binary, not fetched. A browser asking a CDN for its own
# interface font is a flash of unstyled text and a request the user did not
# make -- and this one in particular is served from chrome://weglet/, whose
# CSP has no network source at all, so it could not work anyway.
#
# woff2, not ttf, for a reason that is not only size: WebUIDataSourceImpl
# picks a MIME type from the path and its table has no .ttf in it, so a
# .ttf was served as text/html. Blink is lenient about font MIME types and
# it worked anyway, which is the worst kind of working. .woff2 is in that
# table. It is also about a third of the bytes.
_FONT_FACES = [
    "",
    '@font-face {',
    '  font-family: "Instrument Sans";',
    "  font-weight: 400;",
    "  font-display: block;",
    '  src: url("InstrumentSans-Regular.woff2") format("woff2");',
    "}",
    "",
    '@font-face {',
    '  font-family: "Instrument Sans";',
    "  font-weight: 700;",
    "  font-display: block;",
    '  src: url("InstrumentSans-Bold.woff2") format("woff2");',
    "}",
    "",
    '@font-face {',
    '  font-family: "Outfit";',
    "  font-weight: 400;",
    "  font-display: block;",
    '  src: url("Outfit-Regular.woff2") format("woff2");',
    "}",
    "",
    '@font-face {',
    '  font-family: "Outfit";',
    "  font-weight: 700;",
    "  font-display: block;",
    '  src: url("Outfit-Bold.woff2") format("woff2");',
    "}",
    "",
    '@font-face {',
    '  font-family: "JetBrains Mono";',
    "  font-weight: 400;",
    "  font-display: block;",
    '  src: url("JetBrainsMono-Regular.woff2") format("woff2");',
    "}",
]


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    text = value.lstrip("#")
    return (int(text[0:2], 16), int(text[2:4], 16), int(text[4:6], 16))


def mix(a: tuple, b: tuple, ratio: float) -> tuple[int, int, int]:
    """Matches CSS color-mix(in srgb, a ratio%, b) closely enough.

    Used for the hover tints, which exist in CSS as a mix and are needed in
    TypeScript as channel values -- anim.ts interpolates them per frame, and
    reading a custom property back out of the cascade every frame for every
    control would be the expensive way to get the same numbers.
    """
    return tuple(round(a[i] * ratio + b[i] * (1 - ratio)) for i in range(3))


def write_ts(tokens: dict, out: str) -> None:
    lines = [
        "// Generated by weglet/ui/generate_tokens.py. Do not edit.",
        "// Source: weglet/ui/tokens.json",
        "",
        "// Only for values code has to compute with. Anything that is just",
        "// applied to an element belongs in CSS, through the custom",
        "// properties in tokens.css.",
        "export const tokens = {",
    ]
    for group, name, value in entries(tokens):
        rendered = f'"{value}"' if isinstance(value, str) else str(value)
        lines.append(f"  {ts_name(group, name)}: {rendered},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type TokenName = keyof typeof tokens;")

    # Channel values for the colours anim.ts interpolates. Generated rather
    # than written out again, because a triplet copied by hand is the same
    # number in two places -- and one of these is a mix nobody can recompute
    # by eye.
    colours = {name: value for group, name, value in entries(tokens) if group == "color"}
    ring = hex_to_rgb(colours["ring"])
    field = hex_to_rgb(colours["field"])
    derived = {
        "surface-hover": mix(ring, field, 0.25),
        "surface-pressed": mix(ring, field, 0.40),
    }

    lines += [
        "",
        "// The same colours as channel values. anim.ts interpolates between",
        "// them per frame, so it needs the numbers rather than the strings.",
        "export const channels = {",
    ]
    for name, value in colours.items():
        r, g, b = hex_to_rgb(value)
        lines.append(f"  {ts_name('', name).lstrip('_')}: [{r}, {g}, {b}] as const,")
    for name, triplet in derived.items():
        r, g, b = triplet
        lines.append(
            f"  {ts_name('', name).lstrip('_')}: [{r}, {g}, {b}] as const,"
            f"  // color-mix of ring into field"
        )
    lines += ["} as const;"]

    presets = tokens.get("accentPresets")
    if presets:
        lines += [
            "",
            "// The accent choices offered in settings. The first is the",
            "// default, so 'reset' and the first swatch cannot disagree.",
            "export const accentPresets = [",
        ]
        for preset in presets:
            lines.append(f'  "{preset}",')
        lines += ["] as const;"]

    write(out, "\n".join(lines) + "\n")


def cpp_name(group: str, name: str) -> str:
    """layout-toolbar-height -> kLayoutToolbarHeight."""
    parts = f"{group}-{name}".split("-")
    return "k" + "".join(part.capitalize() for part in parts)


def write_header(tokens: dict, out: str) -> None:
    lines = [
        "// Generated by weglet/ui/generate_tokens.py. Do not edit.",
        "// Source: weglet/ui/tokens.json",
        "",
        "#ifndef WEGLET_UI_TOKENS_H_",
        "#define WEGLET_UI_TOKENS_H_",
        "",
        "namespace weglet::tokens {",
        "",
        "// Logical pixels, the same unit the CSS in the pages uses. The",
        "// window layer converts to device pixels once, at the boundary.",
    ]
    # Only the numeric groups. A C++ constant for a hex colour string would
    # be a colour the C++ side is not the one drawing.
    for group, name, value in entries(tokens):
        if group not in _PIXEL_GROUPS and group not in _MS_GROUPS:
            continue
        lines.append(f"inline constexpr int {cpp_name(group, name)} = {value};")
    lines += [
        "",
        "}  // namespace weglet::tokens",
        "",
        "#endif  // WEGLET_UI_TOKENS_H_",
    ]
    write(out, "\n".join(lines) + "\n")


def write_rust(tokens: dict, out: str) -> None:
    """The one token weglet-profile needs as a Rust constant.

    A fresh profile is created with this colour, and the settings page
    offers the same one as its first swatch. That used to be a literal in
    settings.rs kept honest by build_rust.py reading the .rs file with a
    regular expression and comparing -- a check that could only ever say
    "these two differ", and one that parsed Rust from Python.

    Generating it means there is nothing to check: the profile default and
    the CSS default are one value with one source. Checked in, like
    generated_addresses.rs, so weglet-profile still builds under a plain
    `cargo build`.
    """
    presets = tokens.get("accentPresets") or []
    accent = tokens.get("color", {}).get("accent-solid") or (presets[0] if presets else None)
    if accent is None:
        raise SystemExit(
            "tokens.json has neither color.accent-solid nor accentPresets, "
            "so there is no default accent to generate\n"
        )
    lines = [
        "// Generated by weglet/ui/generate_tokens.py. Do not edit.",
        "// Source: weglet/ui/tokens.json",
        "",
        "// The colour a fresh profile is created with -- the same value",
        "// tokens.css compiles in as --color-accent-solid and the settings",
        "// page offers as its first swatch. One value, one source: a profile",
        "// whose accent does not match the swatch its own page renders by",
        "// default would be a visible bug on first run.",
        f'pub const DEFAULT_ACCENT: &str = "{accent}";',
    ]
    write(out, "\n".join(lines) + "\n")


def write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # Only touch the file when it actually changes: a rewritten timestamp
    # makes ninja rebuild everything downstream for nothing.
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            if handle.read() == contents:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tokens", required=True)
    # All optional: build_ui.py wants the CSS, the TypeScript and the C++
    # header; build_rust.py wants only the Rust one, and asking for it
    # should not mean writing the other three somewhere to throw away.
    parser.add_argument("--css")
    parser.add_argument("--ts")
    parser.add_argument("--header")
    parser.add_argument("--rust")
    args = parser.parse_args()

    if not (args.css or args.ts or args.header or args.rust):
        raise SystemExit("nothing to generate: pass at least one output\n")

    tokens = load(args.tokens)

    # color.accent-solid is the CSS default for the accent, baked in at
    # build time; accentPresets[0] is the same colour offered as the first
    # choice in settings, and weglet-profile's DEFAULT_ACCENT (Rust) is the
    # colour a fresh profile is created with. All three have to be the same
    # value -- a profile whose accent setting does not match the swatch its
    # own CSS renders by default would be a visible bug on first run.
    #
    # They cannot fully collapse into one generated fact: the CSS one is
    # compiled into every page regardless of the user's profile, and Rust's
    # is a compile-time Rust constant a running profile can later diverge
    # from on purpose (the user picked a different colour). What can be
    # enforced is that nobody edits one without editing the others, which
    # this check does at build time rather than leaving it to be noticed by
    # eye.
    accent_solid = tokens.get("color", {}).get("accent-solid")
    presets = tokens.get("accentPresets") or []
    if accent_solid and presets and accent_solid.lower() != presets[0].lower():
        raise SystemExit(
            f"tokens.json: color.accent-solid ({accent_solid}) does not match "
            f"accentPresets[0] ({presets[0]}) -- these are meant to be the "
            "same default accent colour, stated in two forms for two "
            "different consumers (a static CSS token and a settings-page "
            "choice list). Keep them equal.\n"
        )
    if args.css:
        write_css(tokens, args.css)
    if args.ts:
        write_ts(tokens, args.ts)
    if args.header:
        write_header(tokens, args.header)
    if args.rust:
        write_rust(tokens, args.rust)
    return 0


if __name__ == "__main__":
    sys.exit(main())
