#!/usr/bin/env python3
# Copyright 2026 Weglet - Licensed under Apache 2.0
#
# contract.json -> a TypeScript module for the pages, a C++ header for the
# browser, and the internal addresses for weglet-core.
#
# Each output is requested separately; the build asks for what it needs.

import argparse
import json
import os
import sys


def load(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def strip_comments(block: dict) -> dict:
    return {k: v for k, v in block.items() if not k.startswith("$")}


def messages(contract: dict) -> list:
    return contract["messages"]


def pages(contract: dict) -> dict:
    return strip_comments(contract["pages"])


def pushes(contract: dict) -> dict:
    return strip_comments(contract.get("pushes", {}))


def internal_addresses(contract: dict) -> dict:
    return strip_comments(contract.get("internal_addresses", {}))


def ts_identifier(name: str) -> str:
    """security-notice -> securityNotice"""
    head, *rest = name.split("-")
    return head + "".join(part.capitalize() for part in rest)


def cpp_identifier(name: str) -> str:
    """security-notice -> kSecurityNotice"""
    return "k" + "".join(part.capitalize() for part in name.split("-"))


# What a message argument may be, and what the browser checks it against.
# TabId is its own kind: a JavaScript number is a double and cannot hold
# every u64 exactly, so an id crossing as a number could round to a
# different tab.
ARG_KINDS = {
    "string": "kString",
    "number": "kNumber",
    "boolean": "kBoolean",
    "TabId": "kTabId",
}

# The object a push handler is installed on, and the object the browser
# reaches it through. The pages are ES modules, so a bare "setState" is
# nowhere the browser can call it -- CallJavascriptFunctionUnsafe raises a
# ReferenceError in the renderer with nothing on the browser side to
# notice. One constant for both languages, so the two halves cannot pick
# different objects.
PUSH_NAMESPACE = "weglet"


def check(contract: dict) -> None:
    """Everything that would otherwise surface as a confusing compile error
    in generated code -- or, worse, not surface at all."""
    names = [m["name"] for m in messages(contract)]
    if len(names) != len(set(names)):
        raise SystemExit("contract.json has a duplicate message name\n")

    for message in messages(contract):
        for arg in message["args"]:
            if arg not in ARG_KINDS:
                raise SystemExit(
                    f"contract.json: message {message['name']!r} takes an "
                    f"argument of unknown type {arg!r}. Known types: "
                    f"{', '.join(sorted(ARG_KINDS))}.\n"
                )

    known_pages = pages(contract)
    for name, push in pushes(contract).items():
        if push["page"] not in known_pages:
            raise SystemExit(
                f"contract.json: push {name!r} goes to page "
                f"{push['page']!r}, which is not in the pages block.\n"
            )

    functions = [push["function"] for push in pushes(contract).values()]
    if len(functions) != len(set(functions)):
        raise SystemExit("contract.json has a duplicate push function name\n")

    # Two pushes at one page would both install under different names, but
    # the browser picks the function by page, so the second could never be
    # called.
    targets = [push["page"] for push in pushes(contract).values()]
    if len(targets) != len(set(targets)):
        raise SystemExit(
            "contract.json: two pushes target the same page. The browser "
            "chooses the function by page, so only one of them could ever "
            "be sent.\n"
        )

    for name, entry in internal_addresses(contract).items():
        if entry["page"] not in known_pages:
            raise SystemExit(
                f"contract.json: internal address {name!r} resolves to page "
                f"{entry['page']!r}, which is not in the pages block.\n"
            )


def write_ts(contract: dict, out: str) -> None:
    lines = [
        "// Generated by weglet/ui/generate_contract.py. Do not edit.",
        "// Source: weglet/ui/contract.json",
        "",
        "// Tab ids cross as strings: they are u64 on the browser side, and a",
        "// JavaScript number is a double -- it cannot hold every u64 exactly,",
        "// and a silently rounded id shows up as the wrong tab closing.",
        "export type TabId = string;",
        "",
        "// Every message a page may send, as a discriminated union. A name",
        "// that is not here is a compile error rather than a message the",
        "// browser answers by crashing.",
        "export type Outgoing =",
    ]
    for message in messages(contract):
        args = "".join(f", {arg}" for arg in message["args"])
        lines.append(f'  | ["{message["name"]}"{args}]')
    lines[-1] += ";"

    lines += [
        "",
        "// The path each of our pages is served at, under chrome://weglet/.",
        "export const pages = {",
    ]
    for name, path in pages(contract).items():
        lines.append(f'  {ts_identifier(name)}: "{path}",')
    lines += [
        "} as const;",
        "",
        "// The object push handlers are installed on -- see protocol.ts.",
        "// The browser calls `<namespace>.<function>`, so both halves come",
        "// from here rather than being spelled out on either side.",
        f'export const pushNamespace = "{PUSH_NAMESPACE}";',
        "",
        "// The other direction: the function the browser calls on this page.",
        "// Installed under pushNamespace by this name, so the spelling has to",
        "// match the browser's exactly. It did not once, and the new tab page",
        "// received nothing at all.",
        "export const pushes = {",
    ]
    for name, push in pushes(contract).items():
        lines.append(f'  {ts_identifier(name)}: "{push["function"]}",')
    lines += [
        "} as const;",
        "",
        "export type PushName = (typeof pushes)[keyof typeof pushes];",
        "",
        "// The full URL, for the one thing that needs to compare against it:",
        "// recognising one of our own tabs in the tab strip.",
        "export function pageUrl(path: string): string {",
        "  return `chrome://weglet/${path}`;",
        "}",
    ]
    write(out, "\n".join(lines) + "\n")


def rust_identifier(name: str) -> str:
    """security-notice -> SECURITY_NOTICE_ADDRESS, blank-tab -> BLANK_TAB.

    The _ADDRESS suffix matches the names weglet-core used before these were
    generated (SETTINGS_ADDRESS, HISTORY_ADDRESS, ...), so the crate's own
    source did not have to be renamed throughout when this generator took
    over declaring them. blank-tab is the one exception: BLANK_TAB was
    always the const name, with no suffix, so it is kept as it was rather
    than becoming BLANK_TAB_ADDRESS.
    """
    base = name.upper().replace("-", "_")
    return base if name == "blank-tab" else f"{base}_ADDRESS"


def write_rust(contract: dict, out: str) -> None:
    """The addresses side of the contract, for weglet-core.

    Only the addresses, not the messages: the message names are consumed by
    C++ and TypeScript, and weglet-core does not know about chrome.send at
    all -- it is the crate with no IO and no platform. Giving it the whole
    contract would pull browser-process concerns into the one crate that is
    supposed to be free of them.
    """
    addresses = internal_addresses(contract)
    lines = [
        "// Generated by weglet/ui/generate_contract.py. Do not edit.",
        "// Source: weglet/ui/contract.json",
        "",
        "// Weglet's own addresses, in the form the user sees them. The",
        "// browser process maps each to a real chrome://weglet/ page --",
        "// see weglet/browser/weglet_window.cc's ResolveForEngine, which is",
        "// generated from the same source so the two cannot list a",
        "// different set again.",
    ]
    for name, entry in addresses.items():
        lines.append(f'pub const {rust_identifier(name)}: &str = "{entry["address"]}";')
    lines += [
        "",
        "// A page of ours, in the form the user types it. Deliberately exact",
        '// matches: a prefix test would make "weglet://settings.evil.example"',
        "// one of our pages.",
        "pub fn is_internal_address(url: &str) -> bool {",
        "    matches!(",
        "        url,",
    ]
    names = " | ".join(rust_identifier(name) for name in addresses)
    lines.append(f"        {names}")
    lines += ["    )", "}"]
    write(out, "\n".join(lines) + "\n")


def write_header(contract: dict, out: str) -> None:
    all_messages = messages(contract)
    page_names = list(pages(contract))
    max_args = max((len(m["args"]) for m in all_messages), default=0)

    lines = [
        "// Generated by weglet/ui/generate_contract.py. Do not edit.",
        "// Source: weglet/ui/contract.json",
        "",
        "#ifndef WEGLET_UI_GENERATED_CONTRACT_H_",
        "#define WEGLET_UI_GENERATED_CONTRACT_H_",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace weglet::contract {",
        "",
        "// Weglet's own pages live at chrome://weglet/, which is content's",
        "// WebUI scheme with our host on it -- WebUI is what gives a page a",
        "// message channel to the browser, and content grants those bindings",
        "// only on its own scheme.",
        'inline constexpr char kHost[] = "weglet";',
        "",
    ]
    for name, path in pages(contract).items():
        lines.append(f'inline constexpr char {cpp_identifier(name)}Path[] = "{path}";')

    lines += [
        "",
        "// Which of our pages something is.",
        "//",
        "// Worked out once, from the URL a page committed, and carried from",
        "// then on. The browser used to re-derive it by string-comparing the",
        "// committed path against every page on every push -- for every open",
        "// page, on every title change of every tab.",
        "enum class PageKind {",
        "  // Not one of ours, or not committed yet.",
        "  kOther,",
    ]
    for name in page_names:
        lines.append(f"  {cpp_identifier(name)},")
    lines += [
        "};",
        "",
        "struct Page {",
        "  PageKind kind;",
        "  // No leading slash, matching the keys the embedded resource set",
        "  // uses. GetLastCommittedURL().path() carries one; strip it first.",
        "  std::string_view path;",
        "};",
        "",
        f"inline constexpr std::array<Page, {len(page_names)}> kPages = {{",
    ]
    for name, _ in pages(contract).items():
        lines.append(
            f"    Page{{PageKind::{cpp_identifier(name)}, {cpp_identifier(name)}Path}},"
        )
    lines += [
        "};",
        "",
        "inline constexpr PageKind KindForPath(std::string_view path) {",
        "  for (const Page& page : kPages) {",
        "    if (page.path == path) {",
        "      return page.kind;",
        "    }",
        "  }",
        "  return PageKind::kOther;",
        "}",
        "",
        "// What a message argument may be. The browser checks every one",
        "// against this before a handler sees it: a page is our own code, but",
        "// it runs in a renderer, and a compromised renderer is what this",
        "// boundary exists for.",
        "//",
        "// Generated rather than hand-checked per handler. The arities were",
        "// in contract.json all along and only TypeScript used them, so",
        "// changing a message's signature was a compile error on the page",
        "// side and silence in the browser.",
        "enum class ArgKind {",
        "  kString,",
        "  kNumber,",
        "  kBoolean,",
        "  // A u64 tab id, sent as a string and checked to parse as one.",
        "  kTabId,",
        "};",
        "",
        f"inline constexpr size_t kMaxMessageArgs = {max_args};",
        "",
        "struct MessageSpec {",
        "  std::string_view name;",
        "  size_t arity;",
        "  // Only the first `arity` entries mean anything.",
        "  std::array<ArgKind, kMaxMessageArgs> args;",
        "  // False for a message that is registered and only logged. It is",
        "  // still registered: content answers an unregistered chrome.send()",
        "  // by crashing the browser process, so a name here with no callback",
        "  // would be a button that closes the browser rather than one that",
        "  // does nothing.",
        "  bool implemented;",
        "};",
        "",
        f"inline constexpr std::array<MessageSpec, {len(all_messages)}> kMessages = {{",
    ]
    for message in all_messages:
        kinds = [ARG_KINDS[arg] for arg in message["args"]]
        # Padded so every initialiser has the same shape; only `arity`
        # entries are ever read.
        padded = kinds + ["kString"] * (max_args - len(kinds))
        args = ", ".join(f"ArgKind::{k}" for k in padded)
        implemented = "true" if message["implemented"] else "false"
        lines.append(
            f'    MessageSpec{{"{message["name"]}", {len(kinds)}, '
            f"{{{args}}}, {implemented}}},"
        )
    lines += [
        "};",
        "",
    ]

    push_entries = pushes(contract)
    lines += [
        "// The other direction: the JavaScript function the browser calls on",
        "// a page of each kind, qualified by the object protocol.ts installs",
        "// handlers on. Pass it to CallJavascriptFunctionUnsafe as it stands.",
        "//",
        "// Generated because this was the half of the contract nobody",
        "// generated, and the two sides drifted -- the browser called",
        "// weglet.setNewTabState at a page that had installed",
        "// weglet.setNewTab, so the new tab page received nothing and no",
        "// build step noticed. Generating the name alone was not enough:",
        "// the qualifier went missing next, and every push landed on a",
        "// global that ES modules never create.",
        "struct Push {",
        "  PageKind page;",
        "  std::string_view function;",
        "};",
        "",
        f"inline constexpr std::array<Push, {len(push_entries)}> kPushes = {{",
    ]
    for _, push in push_entries.items():
        lines.append(
            f"    Push{{PageKind::{cpp_identifier(push['page'])}, "
            f'"{PUSH_NAMESPACE}.{push["function"]}"}},'
        )
    lines += [
        "};",
        "",
        "// The function to call on a page of this kind, or empty when the",
        "// browser has nothing to push to it.",
        "inline constexpr std::string_view PushFunctionFor(PageKind kind) {",
        "  for (const Push& push : kPushes) {",
        "    if (push.page == kind) {",
        "      return push.function;",
        "    }",
        "  }",
        "  return std::string_view();",
        "}",
        "",
    ]

    addresses = internal_addresses(contract)
    lines += [
        "// Weglet's own addresses, in the form the user sees them, and the",
        "// page each currently resolves to. Generated for Rust too -- see",
        "// generated_addresses.rs -- so the address a tab can be showing",
        "// and the address ResolveForEngine knows how to open are the same",
        "// list by construction. They went out of step once: three of",
        "// these existed on the Rust side with nothing here to resolve",
        '// them, so a tab could carry a human label like "Bookmarks" while',
        "// the URL behind it was a scheme the engine had never heard of.",
    ]
    for name, entry in addresses.items():
        lines.append(
            f"inline constexpr char {cpp_identifier(name)}Address[] = "
            f'"{entry["address"]}";'
        )
    lines += [
        "",
        "struct InternalAddress {",
        "  std::string_view address;",
        "  std::string_view page;",
        "};",
        "",
        f"inline constexpr std::array<InternalAddress, {len(addresses)}>",
        "    kInternalAddresses = {",
    ]
    for name, entry in addresses.items():
        lines.append(
            f"    InternalAddress{{{cpp_identifier(name)}Address, "
            f"{cpp_identifier(entry['page'])}Path}},"
        )
    lines += [
        "};",
        "",
        "}  // namespace weglet::contract",
        "",
        "#endif  // WEGLET_UI_GENERATED_CONTRACT_H_",
    ]
    write(out, "\n".join(lines) + "\n")


def write(path: str, contents: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    # Only touch the file when it changes: a rewritten timestamp makes
    # ninja rebuild everything downstream.
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            if handle.read() == contents:
                return
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract", required=True)
    # All optional: a caller asks for what it needs and nothing else.
    parser.add_argument("--ts")
    parser.add_argument("--header")
    parser.add_argument("--rust")
    args = parser.parse_args()

    if not (args.ts or args.header or args.rust):
        raise SystemExit("nothing to generate: pass at least one output\n")

    contract = load(args.contract)
    # Run whichever output was asked for, so a mistake in contract.json is
    # caught by the first build that reads it.
    check(contract)

    if args.ts:
        write_ts(contract, args.ts)
    if args.header:
        write_header(contract, args.header)
    if args.rust:
        write_rust(contract, args.rust)
    return 0


if __name__ == "__main__":
    sys.exit(main())
