// Generated by weglet/ui/generate_tokens.py. Do not edit.
// Source: weglet/ui/tokens.json

// The colour a fresh profile is created with -- the same value
// tokens.css compiles in as --color-accent-solid and the settings
// page offers as its first swatch. One value, one source: a profile
// whose accent does not match the swatch its own page renders by
// default would be a visible bug on first run.
pub const DEFAULT_ACCENT: &str = "#A855F7";
